name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build aocd-proc
      run: cd aocd-proc && cargo build
    - name: Build aocd
      run: cargo build
    - name: Run tests for aocd-proc
      run: cd aocd-proc && RUST_BACKTRACE=1 cargo test
    - name: Run tests for aocd
      run: RUST_BACKTRACE=1 cargo test
